### ISSUE TITLE
Output point clouds have incorrect intensity

### ISSUE THREAD

**Issue by c7huang** [umautobots/lisnownet#1]
Hi, thanks for publishing the code for your work!
I found that the point clouds saved using `eval.py` do not have correct intensity. When constructing `output_img` in `eval.py`, I believe dimension `1` of `range_img` should be used instead of `0` in order to correctly save the point clouds intensity in `bin` format.
```python
output_img = torch.cat([
    xyz_img,
    range_img[:, 0, :, :].unsqueeze(1),    <--- this should be dimension 1 instead of 0
    residual_img,
    gt_img,
    pr_img
], dim=1)
```

**Comment by tn00364361** [comment]
Thanks for pointing it out. I've made the necessary change to in [dc54ae7](https://github.com/umautobots/lisnownet/commit/dc54ae77879327d41eec94c8b114e6303c79b731)
