### ISSUE TITLE
How to train and test on other dataset? 

### ISSUE THREAD

**Issue by Imp7019** [umautobots/lisnownet#3]
Hello, thank you for your great work, it's really what I need.
I have read the paper and test the model on wads dataset, it works great. 
But when I train on other datasets, all the data becomes nan after convolution.
Could you please tell me how to solve this? Hoping for your reply.

**Comment by Imp7019** [comment]
> Without any error messages, I might not be able to give you any constructive suggestions. However, you can try these things:
> 
> 1. Disable `Fill2d` in the model: comment out line 193 in models.py.
> 2. Make sure that `idx_valid` is not all False: `idx_valid.sum()` must be strickly positive.

Thank you very much. My problem has been resolved due to the calculation of the ring value (line 96 in base. py). After using the ring value from the original dataset, the problem has been resolved.

**Comment by ryanyej** [comment]
Why after Disable Fill2d in the model: comment out line 193 in models.py, loss is not nan ,
not disable is nan?

**Comment by ryanyej** [comment]
yes, because there are at least one line of INC didn't contain any points , so during Fill2d, mu + sigma2.sqrt() will return invalid value.
Then dy = utils.laplacian(y).relu() will return large area of nan.
You should limited your INC ,make sure there are at least one point in each angle.

**Comment by cp3cp** [comment]
It works now! Thanks a lot!
