### ISSUE TITLE
About the Backbone

### ISSUE THREAD

**Issue by kennethleng** [umautobots/lisnownet#4]
Hello author, I would like to ask during the eval process, after the range image is input into the model, what happens to the output y compared to the input range image?
I shall:
         pr_img = delta_d * (delta_i).pow(3) > config.threshold
         pr_img &= xyz_img[:, 2, :, :] > config.z_ground
         pr_img &= range_img[:, 1, :, :] < i_thresh
         pr_img |= range_img[:, 0, :, :] < d_thresh
change into
         pr_img = delta_d * (delta_i).pow(3) > 100000
         pr_img &= xyz_img[:, 2, :, :] > 100000
         pr_img &= range_img[:, 1, :, :] < 0.00001
         pr_img |= range_img[:, 0, :, :] < 0.0001
It is found that the obtained results have no denoising effect, which means that the output y does not remove the noise.
After the range image is input into the model, does the intensity value of the point cloud change?
Thank you so much

**Comment by tn00364361** [comment]
> what happens to the output y compared to the input range image

The output `y` ideally is the cleaned range image.

> does the intensity value of the point cloud change

No.

Your threshold values are too extreme and do not match the physical properties of any real-world point clouds. Please read the comments in `eval.py` to understand how to pick reasonable `d_thresh`, `i_thresh`, and `config.z_ground` values.

As for `config.threshold`, it is a bit more complicated. You should generate scatter plots of `delta_d` v.s. `delta_i` for the entire dataset, and pick a curve that best separates snow points from non-snow points. For example, I picked `delta_d * (delta_i).pow(3) = config.threshold` as the dividing curve for this work.
