### ISSUE TITLE
dataset width question

### ISSUE THREAD

**Issue by ryanyej** [umautobots/lisnownet#5]
Brilliant job!
However, i want to know whether width has to be 2048?
Because the LiDAR we were using was 1800 horizontal.

**Comment by tn00364361** [comment]
The width does not have to be 2048. As you can see in [models.py](https://github.com/umautobots/lisnownet/blob/main/tools/models.py), the bottleneck layer `enc4` has a shape of `(N, C * 16, H // 16, W // 16)`. So the width and height only have to be a multiple of 16.

In your case, 1800 is not a multiple of 16. You'll need padding/cropping or reprojecting the 3D points into a grid with a compatible width.

**Comment by ryanyej** [comment]
OK， thans for your reply .
And out own dataset if use fill2d then loss is nan,
comment out fill2d then loss is normal.
Is fill2d necesary for this denoisy model?
What need to be modified for fill2d to take effect?

**Comment by tn00364361** [comment]
It is not an absolute requirement. We use it to deal with the holes in the range images, as not all pixel has a corresponding 3D point. You can probably use spconv instead of the regular conv2d in the `enc0`, but it's untested.
