### ISSUE TITLE
ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [umautobots/lisnownet#8]
Thank you for your great work and code. When I executed it, I encountered the following issue. Could you please help me resolve it? I am using Python version 3.10.1. Thank you.

when it runs comes to the following line in eval.py
    with Pool(num_proc) as pool:
        pool.map(partial(save_results, log_dir=log_dir), frames)
the error information is as fellows:
ValueError: Exceeds the limit (4300) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

**Comment by tn00364361** [comment]
Try running the function `save_results` with a for-loop, instead of using `multiprocessing.Pool`. This should give you a better idea about where integer-to-string conversion goes wrong.

**Comment by RhythmOfTheRain-Byte** [comment]
> Try running the function `save_results` with a for-loop, instead of using `multiprocessing.Pool`. This should give you a better idea about where integer-to-string conversion goes wrong.

Thank you for your reply. 
I referred to the installation steps in the Dockerfile, 

apt-get install -y --no-install-recommends \
        dvipng \
        cm-super \
        texlive-fonts-recommended \
        texlive-latex-extra

And it worked. Thank you!
